---
abstract: Declare cgiapp runmodes with keywords
author:
- Rhesa Rozendaal <rhesa@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: perl
name: CGI-Application-Plugin-RunmodeDeclare
requires:
  CGI::Application: '4.06'
  Devel::Declare: '0.003001'
resources:
  repository: http://github.com/rhesa/cgi-application-plugin-runmodedeclare
version: '0.09'
